apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-app
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: helm-app
  template:
    metadata:
      labels:
        app: helm-app
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end}}
        release: hyperplane-{{ .Release.Revision }}
    spec:
      imagePullSecrets:
      - name: image-pull-secret
      containers:
      - name: helm-app
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.port | default 80 }}
          name: http
          protocol: TCP
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.port | default 8000 }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds:  {{ .Values.readinessProbe.periodSeconds }}
          successThreshold:  {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds:  {{ .Values.readinessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.port | default 80 }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds:  {{ .Values.livenessProbe.periodSeconds }}
          successThreshold:  {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds:  {{ .Values.livenessProbe.timeoutSeconds }}
        {{- end }}
      tolerations:
      {{- if .Values.tolerations }}
      - effect: {{ .Values.tolerations.effect }}
        key: {{ .Values.tolerations.key }}
        operator: {{ .Values.tolerations.operator }}
        {{- if .Values.tolerations.value }}
        value: {{ .Values.tolerations.value }}
        {{ end }}
      {{ else }}
      - effect: NoSchedule
        key: purpose
        operator: Equal
        value: shakudo-core
      {{ end }}

