{{- $secretObj := (lookup "v1" "Secret" "hyperplane-core" "imagepull-gcr-service-account-key") | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $gcrCredentialJsonB64CL := (get $secretData ".dockerconfigjson") }}

apiVersion: v1
data:
  .dockerconfigjson: {{ $gcrCredentialJsonB64CL }}
kind: Secret
metadata:
  name: image-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
