apiVersion: v1
kind: Service
metadata:
  labels:
    app: helm-app
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.port | default 80 }}
    protocol: TCP
    targetPort: http
  selector:
    app: helm-app
